apiVersion: v1
kind: Service
metadata:
  name: mutating-demo
  namespace: default
spec:
  selector:
    app: mutating-demo
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003
  type: ClusterIP